# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import metrics_pb2 as metrics__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in metrics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MetricServiceStub(object):
    """metrics:
    - keys per minute (KPM)
    - avg mouse speed (pixel dist / min) (px/min)
    - clicks per minute (CPM)
    - active media/song titles every 30 seconds (multiple messages for multiple media)

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetKPMStream = channel.unary_stream(
                '/metrics.MetricService/GetKPMStream',
                request_serializer=metrics__pb2.MetricRequest.SerializeToString,
                response_deserializer=metrics__pb2.MetricResponse.FromString,
                _registered_method=True)
        self.GetMouseSpeedStream = channel.unary_stream(
                '/metrics.MetricService/GetMouseSpeedStream',
                request_serializer=metrics__pb2.MetricRequest.SerializeToString,
                response_deserializer=metrics__pb2.MetricResponse.FromString,
                _registered_method=True)
        self.GetCPMStream = channel.unary_stream(
                '/metrics.MetricService/GetCPMStream',
                request_serializer=metrics__pb2.MetricRequest.SerializeToString,
                response_deserializer=metrics__pb2.MetricResponse.FromString,
                _registered_method=True)
        self.GetMediaStream = channel.unary_stream(
                '/metrics.MetricService/GetMediaStream',
                request_serializer=metrics__pb2.MetricRequest.SerializeToString,
                response_deserializer=metrics__pb2.MetricResponse.FromString,
                _registered_method=True)


class MetricServiceServicer(object):
    """metrics:
    - keys per minute (KPM)
    - avg mouse speed (pixel dist / min) (px/min)
    - clicks per minute (CPM)
    - active media/song titles every 30 seconds (multiple messages for multiple media)

    """

    def GetKPMStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMouseSpeedStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCPMStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMediaStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetricServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetKPMStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetKPMStream,
                    request_deserializer=metrics__pb2.MetricRequest.FromString,
                    response_serializer=metrics__pb2.MetricResponse.SerializeToString,
            ),
            'GetMouseSpeedStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetMouseSpeedStream,
                    request_deserializer=metrics__pb2.MetricRequest.FromString,
                    response_serializer=metrics__pb2.MetricResponse.SerializeToString,
            ),
            'GetCPMStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetCPMStream,
                    request_deserializer=metrics__pb2.MetricRequest.FromString,
                    response_serializer=metrics__pb2.MetricResponse.SerializeToString,
            ),
            'GetMediaStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetMediaStream,
                    request_deserializer=metrics__pb2.MetricRequest.FromString,
                    response_serializer=metrics__pb2.MetricResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'metrics.MetricService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('metrics.MetricService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MetricService(object):
    """metrics:
    - keys per minute (KPM)
    - avg mouse speed (pixel dist / min) (px/min)
    - clicks per minute (CPM)
    - active media/song titles every 30 seconds (multiple messages for multiple media)

    """

    @staticmethod
    def GetKPMStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/metrics.MetricService/GetKPMStream',
            metrics__pb2.MetricRequest.SerializeToString,
            metrics__pb2.MetricResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMouseSpeedStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/metrics.MetricService/GetMouseSpeedStream',
            metrics__pb2.MetricRequest.SerializeToString,
            metrics__pb2.MetricResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCPMStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/metrics.MetricService/GetCPMStream',
            metrics__pb2.MetricRequest.SerializeToString,
            metrics__pb2.MetricResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMediaStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/metrics.MetricService/GetMediaStream',
            metrics__pb2.MetricRequest.SerializeToString,
            metrics__pb2.MetricResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
